// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: extended_dnstap.proto

package dnsutils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendedATags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ExtendedATags) Reset() {
	*x = ExtendedATags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extended_dnstap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendedATags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedATags) ProtoMessage() {}

func (x *ExtendedATags) ProtoReflect() protoreflect.Message {
	mi := &file_extended_dnstap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedATags.ProtoReflect.Descriptor instead.
func (*ExtendedATags) Descriptor() ([]byte, []int) {
	return file_extended_dnstap_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendedATags) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ExtendedNormalize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tld         string `protobuf:"bytes,1,opt,name=tld,proto3" json:"tld,omitempty"`
	EtldPlusOne string `protobuf:"bytes,2,opt,name=etld_plus_one,json=etldPlusOne,proto3" json:"etld_plus_one,omitempty"`
}

func (x *ExtendedNormalize) Reset() {
	*x = ExtendedNormalize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extended_dnstap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendedNormalize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedNormalize) ProtoMessage() {}

func (x *ExtendedNormalize) ProtoReflect() protoreflect.Message {
	mi := &file_extended_dnstap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedNormalize.ProtoReflect.Descriptor instead.
func (*ExtendedNormalize) Descriptor() ([]byte, []int) {
	return file_extended_dnstap_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendedNormalize) GetTld() string {
	if x != nil {
		return x.Tld
	}
	return ""
}

func (x *ExtendedNormalize) GetEtldPlusOne() string {
	if x != nil {
		return x.EtldPlusOne
	}
	return ""
}

type ExtendedFiltering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleRate uint32 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
}

func (x *ExtendedFiltering) Reset() {
	*x = ExtendedFiltering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extended_dnstap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendedFiltering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedFiltering) ProtoMessage() {}

func (x *ExtendedFiltering) ProtoReflect() protoreflect.Message {
	mi := &file_extended_dnstap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedFiltering.ProtoReflect.Descriptor instead.
func (*ExtendedFiltering) Descriptor() ([]byte, []int) {
	return file_extended_dnstap_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendedFiltering) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type ExtendedGeo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City      string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Continent string `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
	Isocode   string `protobuf:"bytes,3,opt,name=isocode,proto3" json:"isocode,omitempty"`
	AsNumber  string `protobuf:"bytes,4,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	AsOrg     string `protobuf:"bytes,5,opt,name=as_org,json=asOrg,proto3" json:"as_org,omitempty"`
}

func (x *ExtendedGeo) Reset() {
	*x = ExtendedGeo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extended_dnstap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendedGeo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedGeo) ProtoMessage() {}

func (x *ExtendedGeo) ProtoReflect() protoreflect.Message {
	mi := &file_extended_dnstap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedGeo.ProtoReflect.Descriptor instead.
func (*ExtendedGeo) Descriptor() ([]byte, []int) {
	return file_extended_dnstap_proto_rawDescGZIP(), []int{3}
}

func (x *ExtendedGeo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ExtendedGeo) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *ExtendedGeo) GetIsocode() string {
	if x != nil {
		return x.Isocode
	}
	return ""
}

func (x *ExtendedGeo) GetAsNumber() string {
	if x != nil {
		return x.AsNumber
	}
	return ""
}

func (x *ExtendedGeo) GetAsOrg() string {
	if x != nil {
		return x.AsOrg
	}
	return ""
}

type ExtendedDnstap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version             string             `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	OriginalDnstapExtra []byte             `protobuf:"bytes,2,opt,name=original_dnstap_extra,json=originalDnstapExtra,proto3" json:"original_dnstap_extra,omitempty"`
	Atags               *ExtendedATags     `protobuf:"bytes,3,opt,name=atags,proto3" json:"atags,omitempty"`
	Normalize           *ExtendedNormalize `protobuf:"bytes,4,opt,name=normalize,proto3" json:"normalize,omitempty"`
	Filtering           *ExtendedFiltering `protobuf:"bytes,5,opt,name=filtering,proto3" json:"filtering,omitempty"`
	Geo                 *ExtendedGeo       `protobuf:"bytes,6,opt,name=geo,proto3" json:"geo,omitempty"`
}

func (x *ExtendedDnstap) Reset() {
	*x = ExtendedDnstap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extended_dnstap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendedDnstap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedDnstap) ProtoMessage() {}

func (x *ExtendedDnstap) ProtoReflect() protoreflect.Message {
	mi := &file_extended_dnstap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedDnstap.ProtoReflect.Descriptor instead.
func (*ExtendedDnstap) Descriptor() ([]byte, []int) {
	return file_extended_dnstap_proto_rawDescGZIP(), []int{4}
}

func (x *ExtendedDnstap) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExtendedDnstap) GetOriginalDnstapExtra() []byte {
	if x != nil {
		return x.OriginalDnstapExtra
	}
	return nil
}

func (x *ExtendedDnstap) GetAtags() *ExtendedATags {
	if x != nil {
		return x.Atags
	}
	return nil
}

func (x *ExtendedDnstap) GetNormalize() *ExtendedNormalize {
	if x != nil {
		return x.Normalize
	}
	return nil
}

func (x *ExtendedDnstap) GetFiltering() *ExtendedFiltering {
	if x != nil {
		return x.Filtering
	}
	return nil
}

func (x *ExtendedDnstap) GetGeo() *ExtendedGeo {
	if x != nil {
		return x.Geo
	}
	return nil
}

var File_extended_dnstap_proto protoreflect.FileDescriptor

var file_extended_dnstap_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x64, 0x6e, 0x73, 0x74, 0x61,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x41, 0x54, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x49, 0x0a, 0x11,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x74, 0x6c, 0x64, 0x5f, 0x70, 0x6c, 0x75, 0x73,
	0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x74, 0x6c, 0x64,
	0x50, 0x6c, 0x75, 0x73, 0x4f, 0x6e, 0x65, 0x22, 0x34, 0x0a, 0x11, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0x8d, 0x01,
	0x0a, 0x0b, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x47, 0x65, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x73, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x73, 0x5f, 0x6f, 0x72, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x4f, 0x72, 0x67, 0x22, 0x88, 0x02,
	0x0a, 0x0e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x44, 0x6e, 0x73, 0x74, 0x61, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x15, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x6e, 0x73, 0x74, 0x61, 0x70, 0x5f, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x44, 0x6e, 0x73, 0x74, 0x61, 0x70, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x24,
	0x0a, 0x05, 0x61, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x54, 0x61, 0x67, 0x73, 0x52, 0x05, 0x61,
	0x74, 0x61, 0x67, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x09, 0x6e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64,
	0x47, 0x65, 0x6f, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6d, 0x61, 0x63, 0x68, 0x61, 0x72, 0x64, 0x2f,
	0x67, 0x6f, 0x2d, 0x64, 0x6e, 0x73, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x3b,
	0x64, 0x6e, 0x73, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extended_dnstap_proto_rawDescOnce sync.Once
	file_extended_dnstap_proto_rawDescData = file_extended_dnstap_proto_rawDesc
)

func file_extended_dnstap_proto_rawDescGZIP() []byte {
	file_extended_dnstap_proto_rawDescOnce.Do(func() {
		file_extended_dnstap_proto_rawDescData = protoimpl.X.CompressGZIP(file_extended_dnstap_proto_rawDescData)
	})
	return file_extended_dnstap_proto_rawDescData
}

var file_extended_dnstap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_extended_dnstap_proto_goTypes = []interface{}{
	(*ExtendedATags)(nil),     // 0: ExtendedATags
	(*ExtendedNormalize)(nil), // 1: ExtendedNormalize
	(*ExtendedFiltering)(nil), // 2: ExtendedFiltering
	(*ExtendedGeo)(nil),       // 3: ExtendedGeo
	(*ExtendedDnstap)(nil),    // 4: ExtendedDnstap
}
var file_extended_dnstap_proto_depIdxs = []int32{
	0, // 0: ExtendedDnstap.atags:type_name -> ExtendedATags
	1, // 1: ExtendedDnstap.normalize:type_name -> ExtendedNormalize
	2, // 2: ExtendedDnstap.filtering:type_name -> ExtendedFiltering
	3, // 3: ExtendedDnstap.geo:type_name -> ExtendedGeo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_extended_dnstap_proto_init() }
func file_extended_dnstap_proto_init() {
	if File_extended_dnstap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extended_dnstap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendedATags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extended_dnstap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendedNormalize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extended_dnstap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendedFiltering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extended_dnstap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendedGeo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extended_dnstap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendedDnstap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extended_dnstap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extended_dnstap_proto_goTypes,
		DependencyIndexes: file_extended_dnstap_proto_depIdxs,
		MessageInfos:      file_extended_dnstap_proto_msgTypes,
	}.Build()
	File_extended_dnstap_proto = out.File
	file_extended_dnstap_proto_rawDesc = nil
	file_extended_dnstap_proto_goTypes = nil
	file_extended_dnstap_proto_depIdxs = nil
}
